### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by mefengl** [mefengl/google-page-translate-button#1]
@ZhangYiBo1998

I tried it, and it works perfectly fine.

Would you like me to publish it?

**Comment by mefengl** [comment]
I think it would be better if you open an account to publish, because this way you can see the plugin data. 

Also, Google plugin developers can form a group to collaborate on developing plugins, but it may not be necessary for this plugin.

**Comment by ZhangYiBo1998** [comment]
Sure, thank you for your help！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mefengl/google-page-translate-button"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 凌晨0:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[mefengl/google-page-translate-button] Chrome Extension (Issue #1)





 
@ZhangYiBo1998
 
I tried it, and it works perfectly fine.
 
Would you like me to publish it?

**Comment by mefengl** [comment]
https://chrome.google.com/webstore/detail/%F0%9F%8D%93-%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91/kgjflbnfgjejlokhfiobjeaeeiciidic

Published!
